// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYaO_mb1sGwiODX7x3do5lwPn95B64PaA',
    appId: '1:529007804807:web:da8bfc7ba883cc8d5a1322',
    messagingSenderId: '529007804807',
    projectId: 'bilgisayarogreniyorum-5a0dc',
    authDomain: 'bilgisayarogreniyorum-5a0dc.firebaseapp.com',
    storageBucket: 'bilgisayarogreniyorum-5a0dc.firebasestorage.app',
    measurementId: 'G-15G4DWXVVN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrKlPS5Pn1SW81VaRxcr3Sie4IR_PESs8',
    appId: '1:529007804807:android:2bc7929b6e04584c5a1322',
    messagingSenderId: '529007804807',
    projectId: 'bilgisayarogreniyorum-5a0dc',
    storageBucket: 'bilgisayarogreniyorum-5a0dc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYVc4KnrmPodhq76qBKomGbhwZdPSWTTU',
    appId: '1:529007804807:ios:be9bebe62befa1955a1322',
    messagingSenderId: '529007804807',
    projectId: 'bilgisayarogreniyorum-5a0dc',
    storageBucket: 'bilgisayarogreniyorum-5a0dc.firebasestorage.app',
    iosBundleId: 'com.example.bilgisayarOgreniyoruz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYVc4KnrmPodhq76qBKomGbhwZdPSWTTU',
    appId: '1:529007804807:ios:be9bebe62befa1955a1322',
    messagingSenderId: '529007804807',
    projectId: 'bilgisayarogreniyorum-5a0dc',
    storageBucket: 'bilgisayarogreniyorum-5a0dc.firebasestorage.app',
    iosBundleId: 'com.example.bilgisayarOgreniyoruz',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAYaO_mb1sGwiODX7x3do5lwPn95B64PaA',
    appId: '1:529007804807:web:95bb9f0cf8593fe05a1322',
    messagingSenderId: '529007804807',
    projectId: 'bilgisayarogreniyorum-5a0dc',
    authDomain: 'bilgisayarogreniyorum-5a0dc.firebaseapp.com',
    storageBucket: 'bilgisayarogreniyorum-5a0dc.firebasestorage.app',
    measurementId: 'G-8ZFVNTZ2N6',
  );
}
